### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by ziqing97** [ziqing97/SateGeoUebung#1]
Hi Nadine,

ich hoffe du kannst die issues per Email bekommen.

danke für die Hinweise über Einheit, das habe ich korrigiert (hoffentlich). Über die ode Funktion: ich finde es unnötig eine 9*1 Vektor einzubauen, sondern wir könnten innerhalb ode "drag_force" anrufen. Das habe ich probiert und du kannst das Ergebnis von"SateUebung_test.m" sehen. 

deine alte Code habe ich nicht geändert, damit du darauf mit deine Idee versuchen möchtest. Und wenn das funktioniert, könnten wir die beide Ergebnisse vergleichen. 

eine Frage ist, diese Kraft von Atmosphäre ist sehr klein, ich weiß nicht ob ihres Einfluss sichtbar ist. 

außerdem ist meine Umlaufbahn zurzeit nur für die initiale Kepler Elemente. Für mehere Bahnen mit verschiedene KE habe ich noch keine Ahnung. (vllt habe ich die Dinge nicht verstanden und falsh gemacht?)

LG, Ziqing

**Comment by siv825** [comment]
Bezüglich Aufrufen der drag_force in der ode-Funktion. Das geht auch nur für GOCE dann aber nicht für Aerobraking, es sei denn man überschreibt das Ergebnis der drag_force für den zweiten Satelliten

**Comment by siv825** [comment]
Von dem gegeben Grafik (siehe unten:) haben wir nur eine einzige Bahn gezeichnet bekommen, aber nicht alle. Ich habe auch keine Ahnung wie man auf die alle kommen soll. Ich würde dazu mal Omid anschreiben. In den Übungen aus dem Bachelor, haben wir auch immer nur eine Spur bekommen. 

![grafik](https://user-images.githubusercontent.com/60197917/99397227-0c101580-28e3-11eb-9ad8-697e7e40202b.png)

**Comment by ziqing97** [comment]
> Bezüglich Aufrufen der drag_force in der ode-Funktion. Das geht auch nur für GOCE dann aber nicht für Aerobraking, es sei denn man überschreibt das Ergebnis der drag_force für den zweiten Satelliten

Du hast recht

**Comment by ziqing97** [comment]
> Von dem gegeben Grafik (siehe unten:) haben wir nur eine einzige Bahn gezeichnet bekommen, aber nicht alle. Ich habe auch keine Ahnung wie man auf die alle kommen soll. Ich würde dazu mal Omid anschreiben. In den Übungen aus dem Bachelor, haben wir auch immer nur eine Spur bekommen.
> 
> ![grafik](https://user-images.githubusercontent.com/60197917/99397227-0c101580-28e3-11eb-9ad8-697e7e40202b.png)

war doof, es gibt natürlich nur einen Bahn, aber die Erder dreht sich. Die Verbesserung habe ich in meine test Funktion gemacht

**Comment by ziqing97** [comment]
jetzt sind ändert sich die Farbe mit verschiedene Breite. Das finde ich nicht schön. Kannst du das verbessern?

**Comment by siv825** [comment]
Danke für die Anpassungen. Jetzt passt alles :)
