### ISSUE TITLE
Aerobraking

### ISSUE THREAD

**Issue by siv825** [ziqing97/SateGeoUebung#2]
Was ist die Höhe von Aerobraking für die drag_force? Haben ja nur hper=120km und hapo=1000km gegeben?

Ich habe es mal mit hapo=h versucht und dann kam nach der nummerische Integration eine Bahn, durch den Ellipsoid raus
![Bahn_Aerobraking_durch_Erde](https://user-images.githubusercontent.com/60197917/99397102-e125c180-28e2-11eb-9233-d8e34fb3d825.jpg)

**Comment by ziqing97** [comment]
Die Höhe ist exakt das Problem hier, weil sie sich ändert immer. Das heißt, die Reibung ist größe an Perigäum und kleiner an Apogäum. Wir müssen die Höhe immer neu rechnen.

**Comment by ziqing97** [comment]
Hallo Nadine,

Das Problem habe ich gelöscht, bitte seh meine test Funktion.

die gegebene Fromel für Aerobrakings Exzentrizität ist leider falsch! 

ich denke die Formel du nutztst für n ist nicht richtig, das soll sqrt(a^3/GM) sein.(nicht r^3)

außdem überlege ich: wir müssen drag_force in ode anrufen. weil die Reibung ist nicht konstant. Wenn du mit 9*1 matrix machst, sind diese Kraft immer gleich, das kann nicht richtig sein(zu mindesten ändert sich die Richtung). Diesen Schritt habe ich für Aerobraking gemacht, für GOCE noch nicht. 

btw, ich habe drag_force verbessert, damit es für Aerobrakingg gut funktioniert. Hauptsache ist, Höhe als input muss jetzt in Meter sein.

**Comment by ziqing97** [comment]
Weitere Fehlern sind ja sehr möglich.

**Comment by siv825** [comment]
Ich habe deine Funktionstruktur von ode für Aerobraking für GOCE übernommen. Für GOCE ist ja die Kraft drag_force ja immer gleich, da die Bahn von GOCE mit e=0 eine Kreisbahn ist.

**Comment by siv825** [comment]
Ich denke, dass der Code jetzt so richtig ist und komplett für die aktuelle Übung. Ich habe nur noch e für Aerobrake umgeschrieben, da ich mit deiner Formel nichts anfangen konnte, aber das Ergebnis war trotzdem richtig. 

LG Nadine
